### ISSUE TITLE
Data Protection on Linux & OSX stores keys unencrypted in the user profile directory

### ISSUE THREAD

**Issue by blowdart** [aspnet/DataProtection#108]
The Data Protection stack creates a key ring and rotates keys on a regular basis. Under OSX and Linux keys are stored unencrypted under the user profile path, in `~/.aspnet/DataProtection-Keys`. 

You should ensure permissions on this directory are limited to the user account your application runs as. You can review permissions with `ls -l path` and adjust permissions using `chmod`. `chmod 700` will limit read, write and execute permissions to the directory owner.

We are still examining options for better protection on these platforms.

**Comment by BrennanConroy** [comment]
~/.aspnet/DataProtection-Keys

**Comment by blowdart** [comment]
Updated. My linux knowledge is so long forgotten.

**Comment by leus** [comment]
Under Linux, is it possible to assert that the directory has the appropriate rights (with some configuration that allows override this assertion?)

**Comment by muratg** [comment]
@leus that would be more or less a sysop responsibility, and I don't think there's a good way to do that from the library itself.

We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
