### ISSUE TITLE
Refactor DI support in DataProtection

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/DataProtection#134]

**Comment by muratg** [comment]
@ajaybhargavb How close is this for check-in?

@Eilon Are we taking this in RC2?  Or postpone to 1.0.0?

**Comment by ajaybhargavb** [comment]
I'll be sending an update to the PR today. But it will not include and test and documentation changes.

**Comment by Eilon** [comment]
I'd like to get this for RC2 because there are public API changes in it, and I spoke to @ajaybhargavb about it and we had a short email thread too.

**Comment by muratg** [comment]
Looks like the PR is a little stale at the moment. Do we have any blockers on this?

**Comment by ajaybhargavb** [comment]
Spoke to @Eilon and @rynowak this morning. This is being moved to RTM.

**Comment by ajaybhargavb** [comment]
The latest code and samples are in https://github.com/aspnet/DataProtection/tree/ajbaaska/new-dataprotection branch.

**Comment by GuardRex** [comment]
@ajaybhargavb You're working on the DI bits, right? I ask because I was having a small problem with DI into the `XmlDecryptor`. https://github.com/aspnet/DataProtection/issues/154

The problem was that DI for `XmlDecryptor` wasn't working. I wanted to do this ...
```
public CustomXmlDecryptor(IOptions<CustomDataProtectionOptions> dataProtectionOptions)
{
    _key = dataProtectionOptions.Value.Key;
}
```
... but that wasn't working. I simply wasn't getting the value. It works using the ctor injection pattern for `XmlEncryptor`, just not for `XmlDecryptor`. 

With a little help from @tillig, I was able to make it work on the decryptor side with a little hack, I ended up having to do this ...
```
public CustomXmlDecryptor(IServiceProvider services)
{
    var dataProtectionOptions = 
        services.GetRequiredService<IOptions<CustomDataProtectionOptions>>();
    _key = dataProtectionOptions.Value.Key;
}
```
Is fixing this something that falls under this issue, or was this problem already addressed do you know?

**Comment by rynowak** [comment]
@GuardRex - please make a separate issue for this. Having looked at the code, this isn't something that's been supported so far so it's a feature request

**Comment by GuardRex** [comment]
@rynowak Ok, thanks. Will do.

**Comment by GuardRex** [comment]
I reopened and re-titled that issue ... it basically describes the difference in success using DI with the ctors of `IXmlDecryptor` and `IXmlEncryptor`. Given the workaround there, I'm not blocked of course, so it really is just a nice-to-have if you like the idea.

https://github.com/aspnet/DataProtection/issues/154
