### ISSUE TITLE
Provide a way to initialize the data protection key from a byte array

### ISSUE THREAD

**Issue by Flavien** [aspnet/DataProtection#167]
Along with `PersistKeysToFileSystem` and `PersistKeysToRegistry`, there should be a method that allows you to pass a byte array, encryption algorithm and hashing algorithm, which are then used as the data protection key.

It doesn't really seem to make sense that the only way to pass the data protection key is via an XML structure.

This new method would allow anyone to provide a key coming from any other source (Azure, AWS, configuration, env variable, etc.)

**Comment by GuardRex** [comment]
You're addressing two different things: the repository is separate from the encryption/decryption bits. You can replace the default `IXmlRepository` for the location of the key ring, while you can replace the `IXmlEncryptor` and `IXmlDecryptor` with your own implementations that will address the latter.

For some info along these lines, see https://github.com/aspnet/DataProtection/issues/92. Also note that the team is going to provide repositories for Azure Blob/Table Storage and a tie-in to Azure Key Vault.

**Comment by Flavien** [comment]
Sure, then disregard my comment about storage on Azure.

I want to take care myself of distribution and persistence of the data protection key, and I need a way to setup the data protection services from my own key, directly as a parameter.

What I need is another implementation of ``IKeyManager`` which is **not** XML based, with the convenience extension method to set it up from the ``IServiceCollection``.

**Comment by GuardRex** [comment]
I don't recall anyone discussing that aspect (replacing `IKeyManager`). I'm using their XML-based key ring (with a custom Azure Table Storage repository); however, I encrypt/decrypt the keys in the key ring with my own encryptor/decryptor whose master key is stored in Azure Key Vault (because I didn't want to maintain certs on servers across a webfarm). All of the code I wrote will be going away when the team delivers the new Azure features for my apps.

**Comment by blowdart** [comment]
The library is designed so people don't override the decisions with their own keys etc., because frankly people get that wrong. It's meant as a black box that does the right thing.

Blob/Table storage is coming (I have a meeting this week about what we need to develop for data protection next - now is a good time to ask *grin*), but key vault is a more interesting problem, given it's purpose is to never serve you keys. So you'd have to store keys as secrets, and they don't have a way to give us all secrets (instead you page, and page, and page) and creating new secrets in code needs elevated rights (which you never want to grant your app)

**Comment by GuardRex** [comment]
You seem to be saying there is a problem with using Azure Key Vault in the DP ecosystem as it stands today.

I'm not 100% clear on the problem: My idea is that if the key that is used to encrypt and decrypt the key ring is put into Azure Key Vault so that one wouldn't need to mess with maintaining certificates on servers (even locally on the dev machine, Azure Key Vault sends down the key). Then, as in my case, if you have Azure Table Storage (or Blob Storage) for the repository, then one also wouldn't have to configure network shares across a webfarm (again, the dev machine also uses Azure for the repository in development). If one wanted to separate concerns between dev, staging, production, they would swap in a different Key Vault endpoint and a different Table/Blob Storage account (or table/container).

I must be misunderstanding what you're saying about a problem with this setup ... perhaps it's not what you were intending to offer WRT to the Azure Key Vault part of the setup. Were you thinking more along the lines of Key Vault being used **AS** the key ring repository itself?

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
