### ISSUE TITLE
Data protection system is far too onerous by default

### ISSUE THREAD

**Issue by Tratcher** [aspnet/DataProtection#192]
_From @atrauzzi on December 14, 2016 15:34_

https://github.com/aspnet/Home/issues/466

https://github.com/aspnet/DataProtection/issues/115

I've just had my hands forced into the data protection system with something I'm working on and I absolutely cannot believe how complicated this has been made and how many assumptions have been dumped on developers.

Why can't I just put a string in my environment and be done with it?

I know what the security concerns are, but ratcheting things up like this is too much too early!  Especially when the only default implementations available assume a shared filesystem between machines - completely unrealistic!

I'm not encrypting anything that is sensitive at the moment, frankly just signing my information to prevent tampering would be sufficient in my situation.

This has to be pointed out: https://github.com/aspnet/Home/issues/466#issuecomment-205832926

Maybe there just needs to be a guide or some code snippets, but here's what I need:

 - Let me manage my own business
 - A key in my `appsettings.json`
 - Tell the data protection system to use that
 - If I want to encrypt at-rest, I'll opt-in
 - If I want to secure access to the at-rest data, I'll opt-in
 - Get out of my way!

In terms of right away, any guidance on just getting this very overbearing and time consuming design off of my back would be very greatly appreciated.

_Copied from original issue: aspnet/Security#1071_

**Comment by Tratcher** [comment]
Existing configuration docs (which don't directly cover this scenario): https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview

**Comment by atrauzzi** [comment]
Thanks @Tratcher!  Apologies for the wrong repo.

**Comment by GuardRex** [comment]
@atrauzzi PM me on Slack when you get a chance. I have some info for you on this issue.

**Comment by blowdart** [comment]
// A key in my appsettings.json

Yea ... we have a huge problem with that. It bit us with web.config and machine key, and frankly we worked very hard to avoid it this time around.

**Comment by atrauzzi** [comment]
@blowdart - It's not really your job to remove choice by imposing a single assumption about what peoples' deployment scenarios are to look like.

I don't want to link all my nodes to a shared filesystem.  Period.

"**_we_** have a huge problem with that. It bit **_us_** with web.config and machine key"

Nothing suspicious to you about that language?

I haven't had issues with a constant key in the past in other frameworks.  I'm not saying **_your_** prescribed solution isn't warranted in specific circumstances.  But these are not the kinds of decisions the framework should be imposing.

It's not your job to put nerf tips on everything and wrap us in bubble wrap.  Offer simple defaults, offer good advice, sure.  But the level of security going on here blows most small projects' budgets.

**Comment by blowdart** [comment]
And you don't have to link to a file system. You can link, with our packages, to azure storage, to a redis cache, to the registry.

It is my job to ensure ASP.NET is secure by default, and if that means making decisions around defaults then that's what I'll do. There are extension points so if you want to shoot yourself in the foot by using a single key, stored in config, that never rotates then you can implement a keystore to do so. It's a simple interface, it needs two methods implemented. You can even publish as a nuget package.

Using a fixed key is not good advice, and it's not something we will implement, or take a PR for.

**Comment by atrauzzi** [comment]
Hang on.  First thing: There's no need to talk down to me.

 - Running a redis cache is an additional cost for most
   - Managed redis on Azure pricing is prohibitively expensive
 - Azure storage is azure specific or if self-implemented via any possible mongodb support has the same issues as running a redis cache
 - Registry??

I understand you take this role seriously, but you rushed past my issues and fail to acknowledge that other frameworks get by just fine without such a tight-fisted policy.  If it was nearly as pandemic-proportioned as you're implying, there would be some pretty decent fodder for news out there.

I'm not daft, I already acknowledged the superiority of your design in terms of what it accomplishes.  It's the necessity in the scope of smaller projects I'm talking about here.

**Comment by blowdart** [comment]
This isn't talking down, if it comes off like that then I apologise.

We've had the other frameworks argument internally before, and my response to everyone is, when it's security related, it's not enough to be as bad as everyone else, we have to be _better_.

There have been numerous MSRC cases around machine key, including one where we, for the first time ever, deliberately broke back compatibility to fix what ended up as remote code execution, and part of that was machine key related. Having an encryption key that is impossible to roll successfully is not somewhere we're going back to, and like I say, the extensibility points are there to do what you want. It's like basic authentication. It's horrible from a security perspective, and we won't put it into asp.net, but the extension points are there, and you can write your own, I did it as an exercise.

**Comment by atrauzzi** [comment]
You're mis-characterizing the request by saying "as bad as everyone else".  It's good enough, independently of your experiences.
The answer that people are free to implement their own is just as universally unhelpful as well.  Especially given how tricky the extension points are.

I've spent two days fighting with this nonsense.  Believe me, I've plugged into other frameworks without issue, this is not my first rodeo.

To that end: I'm right now having a particular issue right now trying to get my identity key over to ASP.net 4.  I actually made a passthrough `IDataProtector` -- literally `return the byte[]` and am still getting _"SessoinId missing"_ from `Microsoft.Owin.Security.Cookies.CookieAuthenticationMiddleware`.  I can literally base64 decode the identity cookie content and read it, and it's still not working!?

Have completely given up trying to get sources and symbols working locally because that was another yak shave.  This system is completely user unfriendly and it's half due to the fact that I was goaded into trying to dial it down.

_"Not somewhere we're going back to."_

Way too hard-line a stance.  By the sheer number of users, this sky is falling language isn't convincing in terms of what the defaults should be.

https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/railties/lib/rails/generators/rails/app/templates/config/secrets.yml#L21

https://github.com/laravel/laravel/blob/master/config/app.php#L106

https://github.com/playframework/play-scala/blob/master/conf/application.conf#L43

https://github.com/openshift/django-example/blob/master/wsgi/myproject/myproject/settings.py#L28

These systems are easy to use and would have me up and running blisteringly faster than ASP.net would if I could use them.  Does that make ASP.net more or less competitive in the framework space?

**Comment by blowdart** [comment]
Ah hold on, you want to share identity cookies between a 4.5 app and .NET Core? Data Protection is only half the problem, the ticket format also changed. That scenario is supported, and documented. What you do is replace the ticket formatter, and the stuff that machine key does with a forward compat package, which has ASP.NET 4.5 use data protection and the new ticket format. While the instructions are on the docs site they're not exactly well written, so I ended up doing a step by step guide, as a request for comments, on https://github.com/blowdart/idunno.CookieSharing

**Comment by atrauzzi** [comment]
Sadly those instructions are exactly what I followed to get into this mess.

I know exactly where you'll want to draw attention to because it's the one line I've deviated from:

```
var ticketFormat = new AspNetTicketDataFormat(new DataProtectorShim(passthroughDataProtector));
```

Instead, mine looks like this:

```
using Microsoft.Owin.Security.DataProtection;

namespace MyApp.Web.Authentication
{
    public class PassthroughDataProtector : IDataProtector
    {
        public byte[] Protect(byte[] userData)
        {
            return userData;
        }

        public byte[] Unprotect(byte[] protectedData)
        {
            return protectedData;
        }
    }
}
```

My suspicion is that that something seems wrong in the interop code ASP.net 4 uses, because using my temporary passthrough data protector above, my cookie is:

```
CookieCookie5Microsoft.AspNetCore.Authentication.Cookies-SessionId$01997a1a-b4cb-43cb-a44b-2a678d58c0d8Cookie
```

And yet on ASP.net 4 I'm being told that the SessionId is missing.  Remember throughout this: I want my own data protector -- and as I mentioned earlier, I'd be perfectly fine just signing the data to make sure it hasn't been tampered with.  I don't need to go the whole 9 yards.

**Comment by blowdart** [comment]
How weird, it works on my machine. So as of next week I have 3 weeks vacation, where I will be ignoring most work emails, so I have time to catch up on my backlog of writing templates and demo code. What'll I do is spin up a "horrid" data protector which uses a fixed value, and go from there and see if I can replicate this.

**Comment by atrauzzi** [comment]
That sounds good, thanks!  I'm not sure what I can do in the meantime, but I'll keep nipping at the edges of this I guess, I feel like I've gone as far as I can unless I can magically convince VS to let me debug the code.  But that's been a totally separate nightmare.

**Comment by blowdart** [comment]
Yea that's not easy. What you end up doing is cloning the repo, and then adding references. @HaoK might be able to help with that, he walked me through it last time I tried to do it.

**Comment by atrauzzi** [comment]
So, the first miracle is that I actually managed to get debugging the code.  At which point it became immediately apparent to me that the key it's using is `Microsoft.Owin.Security.Cookies-SessionId`.

Unfortunately the second miracle is that I now have a pretty clear idea of what's happening:

```
private const string SessionIdClaim = "Microsoft.Owin.Security.Cookies-SessionId";
```

I guess I'm stuck subclassing another class now (`CookieAuthenticationHandler`) to come up with my own string value there.  I've totally said this before and I know it's a pain to bring it up again - but I'm really convinced that if the whole ASP.net team just spent a couple of weeks studying Laravel, you'd get some ideas on how to improve extensibility.  

That said, things aren't *too* far off.  The two are so very similar and not coincidentally, the creator of Laravel used to be a .net dev.

**Comment by atrauzzi** [comment]
@blowdart - By no stretch am I expecting you to beam when you see it, but I spent today throwing lots of wrenches at data protection: https://github.com/atrauzzi/praxis/tree/master/Praxis/DataProtection

More or less nopes out of everything.

On the brighter side, I know the interfaces a little bit better now...even if I'm not intending to use them!

**Comment by blowdart** [comment]
I'm going to go cry in a corner now 😭

**Comment by HaoK** [comment]
Perhaps it is a good thing its so hard to remove, since this seems like a very bad idea to disable dataprotection :)

**Comment by atrauzzi** [comment]
At least I can parse the cookie in both my applications now.

I'll probably make one that signs the data, similar to JWS.  That at least prevents tampering.

There are plenty of applications out there that don't go to the degree the default ASP.net setup does.
